export const speciesList = 
    [
    "Abomena Pahidermo",
    "Alta Koltuko",
    "Arba Brakumo",
    "Arbara Krono",
    "Arda Vosto",
    "Avka Felo",
    "Bera Manganto",
    "Brila Ornamo",
    "Cielarka Cimo",
    "Degela Koro",
    "Dentega Salto",
    "Dormema Ventreto",
    "Dorna Maco",
    "Ebena Kuranto",
    "Ekvinoska Kavigo",
    "Etarakido",
    "Flirtanta Flamo",
    "Floranta Doloro",
    "Fluganta Rato",
    "Frida Fisisto",
    "Furioza Vizago",
    "Glacia Alsalto",
    "Glita Skvamo",
    "Glubleko",
    "Gudra Kornaro",
    "Imsanga Afero",
    "Inkuba Brulajo",
    "Kasa Gardanto",
    "Kauri Makzelo",
    "Klara Alsalto",
    "Klipeta Kapto",
    "Koleratako",
    "Kora Voko",
    "Kosmira Girafo",
    "Kvieta Kiraso",
    "Lanuga Vizago",
    "Limaka Cevalo",
    "Luma Mordo",
    "Luna Hundo",
    "Malbenita Beno",
    "Malvolva Kapo",
    "Membra Cerbo",
    "Minuskla Casadisto",
    "Monta Selo",
    "Muska Felo",
    "Muskbirdo",
    "Nebula Glisanto",
    "Nektara Veziko",
    "Netimo",
    "Nokta Voko",
    "Okula Pikilo",
    "Ombra Vesperto",
    "Osta Frakaso",
    "Pieda Pastigo",
    "Pompaca Floro",
    "Ranbleko",
    "Reganta Plumaro",
    "Rida Frakaso",
    "Ruzafolio",
    "Sabla Rego",
    "Saltanta",
    "Sauma Kudrilo",
    "Sencesa Simfonio",
    "Senfina Krizo",
    "Senvida Naganto",
    "Silenta Spuristo",
    "Songa Kreinto",
    "Stepa Safido",
    "Stranga Sciuro",
    "Strigosto",
    "Suna Hundo",
    "Tagalo",
    "Tagluma Valso",
    "Tera Girafo",
    "Terura Fisisto",
    "Timiga Dancanto",
    "Toksa Muko",
    "Tonbleko",
    "Transira Alsalto",
    "Vetura Oazo",
    "Vira Beko"
]